version: "{build}"

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master

# Uncomment to debug via RDP
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  NSSM_VERSION: "2.24-23-gfb96938"
  RUBY_VERSION: "22-x64"   # https://www.appveyor.com/docs/installed-software#ruby

install:
  - ps: packaging\msi\install.ps1

build_script:
  - ps: packaging\msi\build.ps1

test_script:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - bundler --version
  - ps: packaging\msi\test.ps1

artifacts:
- path: output/*.msi
  name: Release
deploy:
- provider: GitHub
  auth_token:
    secure: FA0xahKGq6AVJEOd1Oen0xPbbM3C9qETfDj69A93xeVyLDlQazwyJa1Si6fn8OMo
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
